### ISSUE TITLE
Invert italics in figcaption

### ISSUE THREAD

**Issue by tuskpot** [standardebooks/rudyard-kipling_just-so-stories#2]
While fixing a nearby error, I noticed that \<em\> inside \<figcaption\> doesn't invert the italics. Here is a sample of the code from the last illustration in "The Beginning of the Armadillo":

`<figcaption>`
`[…] and the Tortoise <em>and</em> the Armadillo […]`
`</figcaption>`

Because the content of figcaption is in italics, I would expect the emphasized "and" to be in straight letters, but it seems to be italicized like the rest of the caption.

**Comment by acabal** [comment]
Good catch, I've updated the CSS to handle this. Thanks!
