### ISSUE TITLE
Duplicate question word in "The Elephant's Child"

### ISSUE THREAD

**Issue by solt87** [standardebooks/rudyard-kipling_just-so-stories#4]
In the poem at the end of the chapter "The Elephant's Child",
the question word "Where" appears twice, both on line 3 and 4.
It seems like a mistake; one of them ought to be "Why".

[This](https://www.gutenberg.org/cache/epub/2781/pg2781-images.html#link2H_4_0005) Project Gutenberg copy has "Why" instead of "Where" on line 4,
whereas [this](https://allpoetry.com/I-Keep-Six-Honest-Serving-Men) page has "Why" instead of "Where" on line 3. I don't know
which form is the original one, but the two "Where"s seem to be wrong.

(Also, the second linked version has a comma at the end of line 9,
but the PG and SE version has a full stop, which seems odd between
the two sentences. Shouldn't it be a comma?)

**Comment by acabal** [comment]
The page scans of a [1902 edition](https://babel.hathitrust.org/cgi/pt?id=nc01.ark:/13960/t34182040&seq=95&q1=%22I+keep+six+honest%22) and also a [1912 edition](https://www.google.com/books/edition/Just_So_Stories/RwBbAAAAMAAJ?hl=en&gbpv=1&dq=%22I%20keep%20six%20honest%22&pg=PA81-IA2&printsec=frontcover) have two `Where`s, so it might be that the PG transcription is incorrect.

**Comment by acabal** [comment]
The comma does appear to be a typo, and I've fixed that. Thanks!
